ImagesP
std::vector<Point> ImagesP::all_block
Referenced by Core::blockProcessing, markersProcessing, startBlock.
Point ImagesP::posCar
Referenced by markersProcessing, init, readyForPath, getCarPosition, trackingCar.
Point ImagesP::posArrival
Referenced by markersProcessing, init, readyForPath, getArrivalPosition.
float ImagesP::angleCar
Referenced by markersProcessing, trackingCar.
float ImagesP::angleArrival
Referenced by markersProcessing.
MarkerDetector ImagesP::MDetector
Referenced by calibration.
std::vector<Marker> ImagesP::Markers
Referenced by getSizeMarker, markersProcessing, calibration, trackingCar.
Mat ImagesP::markerImg
Referenced by init, calibration.
Mat ImagesP::markerCpy
Referenced by markersProcessing, init.
VideoCapture ImagesP::cap
Referenced by ~ImagesP, init, calibration.
ImagesP::ImagesP()
References init.
ImagesP::~ImagesP()
References cap.
bool ImagesP::readyForPath()
References posCar, posArrival.
Referenced by Core::blockProcessing.
void ImagesP::startBlock()
References all_block, loadCalib, markersProcessing.
Referenced by Core::blockProcessing.
void ImagesP::saveCalib(std::string str)
Referenced by calibration.
Point2f ImagesP::loadCalib()
Referenced by Core::calibration, startBlock.
void ImagesP::calibration()
References saveCalib, cap, markerImg, MDetector, Markers, MARKER_ID_AREA, TIMEOUT_CALIBRATION.
Referenced by Core::calibration.
Point ImagesP::getCarPosition()
References posCar.
Referenced by Core::blockProcessing.
Point ImagesP::getArrivalPosition()
References posArrival.
Referenced by Core::blockProcessing.
uint8_t ImagesP::getSizeMarker()
References Markers.
Referenced by Core::blockProcessing.
void ImagesP::trackingCar()
References posCar, angleCar, Markers, MARKER_ID_CAR, getAngle.
void ImagesP::init()
References cap, CAM_EXTERN, markerCpy, markerImg, posCar, posArrival.
Referenced by ImagesP.
void ImagesP::markersProcessing(Point2f centerPt)
References Markers, MARKER_ID_AREA, drawMatrix, markerCpy, MARKER_ID_CAR, MARKER_ID_ARRIVAL, fillRotatedRect, getAngle, getBlockMatrix, MARGE_BLOCK_PROCESSING, willbeBlock, getXYMatrix, all_block, angleCar, posCar, angleArrival, posArrival.
Referenced by startBlock.
Point ImagesP::getXYMatrix(int16_t x_matrix, int16_t y_matrix)
Referenced by markersProcessing.
Point2f ImagesP::getBlockMatrix(Point2f center, int16_t x_pixel, int16_t y_pixel)
Referenced by markersProcessing.
float ImagesP::getAngle(Marker marker)
Referenced by markersProcessing, trackingCar.
void ImagesP::drawMatrix(Mat &frame, Point center)
Referenced by markersProcessing.
bool ImagesP::willbeBlock(Mat &frame, Point leftTop, int8_t pixelMax)
Referenced by markersProcessing.
void ImagesP::fillRotatedRect(Mat &frame, Point2f center, Size2f size, Scalar color, float angle)
Referenced by markersProcessing.