Path
vector<pair<int8_t,int8_t> >* Path::list_path
Referenced by Core::drawDebug, Manager::update, add, remove, has, toString.
Path * Path::instance
Referenced by getInstance.
Path * Path::getInstance()
References instance, Path.
Referenced by Manager::Manager.
bool Path::add(int8_t x, int8_t y) override
References list_path.
Referenced by Core::pathfinding.
bool Path::remove(int8_t x, int8_t y) override
References has, list_path.
bool Path::has(int8_t x, int8_t y) override
References list_path.
Referenced by remove.
bool Path::clear() override
Referenced by Manager::reset.
string Path::toString() override
References list_path.
Referenced by Manager::toString.
Path::~Path()
Path::Path()
Referenced by getInstance.