End
End * End::instance
Referenced by getInstance.
pair<int8_t, int8_t>* End::position
End * End::getInstance()
References instance, End.
Referenced by Manager::Manager.
bool End::setPosition(int8_t x, int8_t y) override
Referenced by Core::blockProcessing, Manager::reset.
pair<int8_t, int8_t> End::getPosition() override
Referenced by Core::drawDebug, Core::pathfinding, toString, Manager::update.
std::string End::toString() override
References getPosition.
Referenced by Manager::toString.
End::~End()
End::End()
Referenced by getInstance.