Chemin
vector<pair<int8_t,int8_t> >* Chemin::list_chemin
Referenced by add, Core::drawDebug, has, remove, toString, Manager::update.
Chemin * Chemin::instance
Referenced by getInstance.
Chemin * Chemin::getInstance()
References Chemin, instance.
Referenced by Manager::Manager.
bool Chemin::add(int8_t x, int8_t y) override
References list_chemin.
Referenced by Core::pathfinding, unitest_pathfinding.
bool Chemin::remove(int8_t x, int8_t y) override
References has, list_chemin.
bool Chemin::has(int8_t x, int8_t y) override
References list_chemin.
Referenced by remove.
bool Chemin::clear() override
Referenced by Manager::reset.
string Chemin::toString() override
References list_chemin.
Referenced by Manager::toString.
Chemin::~Chemin()
Chemin::Chemin()
Referenced by getInstance.