PathFinding
Cellule* PathFinding::_pathfinding
Referenced by findPath, getChemin, hasPossibility, PathFinding, ~PathFinding.
std::vector<std::pair<int8_t,int8_t> >* PathFinding::list_cheminOk
Referenced by getChemin, PathFinding, ~PathFinding.
std::vector<Cellule*> PathFinding::all_cellules
Referenced by getCellule, PathFinding, ~PathFinding.
std::vector<Cellule*> PathFinding::current_list
Referenced by findPath, PathFinding, ~PathFinding.
int8_t PathFinding::width
Referenced by getCellule, PathFinding, surroundedBlocs.
int8_t PathFinding::height
Referenced by getCellule, PathFinding, surroundedBlocs.
std::pair<int8_t, int8_t> PathFinding::start_coord
Referenced by getChemin, PathFinding.
std::pair<int8_t, int8_t> PathFinding::end_coord
Referenced by findPath, PathFinding.
PathFinding::PathFinding(int8_t **matrice, int8_t width_scene, int8_t height_scene, std::pair< int8_t, int8_t > start, std::pair< int8_t, int8_t > end)
References _pathfinding, all_cellules, BLOC_DEF, current_list, end_coord, Cellule::everfind, findPath, getCellule, height, list_cheminOk, Cellule::m_P, start_coord, surroundedBlocs, width.
bool PathFinding::everParent(Cellule *current, Cellule *parent)
References Cellule::m_parent.
Referenced by findPath.
bool PathFinding::hasPossibility()
References _pathfinding.
Referenced by Core::pathfinding, unitest_pathfinding.
std::vector<std::pair<int8_t, int8_t> >* PathFinding::getChemin()
References _pathfinding, Cellule::everfind, Cellule::getCoord, list_cheminOk, Cellule::m_parent, start_coord.
Referenced by Core::pathfinding, unitest_pathfinding.
PathFinding::~PathFinding()
References _pathfinding, all_cellules, current_list, list_cheminOk.
void PathFinding::findPath()
References _pathfinding, current_list, end_coord, everParent, getCellule, Cellule::getCoord, Cellule::m_P, Cellule::m_parent.
Referenced by PathFinding.
Cellule* PathFinding::getCellule(int8_t x, int8_t y)
References all_cellules, height, width.
Referenced by findPath, PathFinding.
bool PathFinding::surroundedBlocs(int8_t x, int8_t y, int8_t **matrice)
References height, width.
Referenced by PathFinding.