Arrive
Arrive * Arrive::instance
Referenced by getInstance.
pair<int8_t, int8_t>* Arrive::position
Arrive * Arrive::getInstance()
References Arrive, instance.
Referenced by Manager::Manager.
bool Arrive::setPosition(int8_t x, int8_t y) override
Referenced by Core::blockProcessing, Manager::reset, unitest_pathfinding.
pair<int8_t, int8_t> Arrive::getPosition() override
Referenced by Core::drawDebug, Core::pathfinding, toString, unitest_pathfinding, Manager::update.
std::string Arrive::toString() override
References getPosition.
Referenced by Manager::toString.
Arrive::~Arrive()
Arrive::Arrive()
Referenced by getInstance.