Core
struct _stateMachine Core::stateMachine
Referenced by autoVirtualMode, blockProcessing, calibration, init, pathfinding, setMode, start, trajectory.
bool Core::changeMode
Referenced by init.
Mode Core::avm_mode
Referenced by getCurrentMode, listenIPC, setMode, start.
Manager* Core::manager
Referenced by blockProcessing, drawDebug, init, pathfinding, setMode, ~Core.
ImagesP* Core::process
Referenced by blockProcessing, calibration, ~Core.
PathFinding* Core::path
Referenced by pathfinding, setMode, ~Core.
Core::Core()
References init.
Core::~Core()
References manager, path, process.
bool Core::start()
References _stateMachine::_statePathfinding, Auto_Mode, autoVirtualMode, avm_mode, DEBUG, drawDebug, init, listenIPC, Manual_Mode, manualMode, OK, stateMachine, Stop_Mode, Virtual_Mode.
Referenced by main.
bool Core::stop()
bool Core::reset()
void Core::drawDebug(Mat &frame)
References Manager::arrive, Manager::bloc, Manager::car, Manager::chemin, Car::getPosition, Arrive::getPosition, Bloc::list_bloc, Chemin::list_chemin, manager.
Referenced by start.
bool Core::init()
References _stateMachine::_stateCalibration, _stateMachine::_stateImageBlock, _stateMachine::_stateIPC, _stateMachine::_statePathfinding, _stateMachine::_stateServer, _stateMachine::_stateTrajectory, changeMode, Manager::getInstance, Manager::initScene, manager, NONE, setMode, stateMachine, Stop_Mode.
Referenced by Core, start.
bool Core::restartServer()
void Core::setMode(Mode _mode)
References _stateMachine::_stateImageBlock, _stateMachine::_statePathfinding, _stateMachine::_stateTrajectory, avm_mode, manager, NONE, path, Manager::reset, stateMachine.
Referenced by autoVirtualMode, init, listenIPC.
Mode Core::getCurrentMode()
References avm_mode.
void Core::listenIPC()
References Auto_Mode, avm_mode, setMode.
Referenced by start.
void Core::autoVirtualMode(bool is_auto)
References _stateMachine::_stateCalibration, _stateMachine::_stateImageBlock, _stateMachine::_statePathfinding, _stateMachine::_stateServer, _stateMachine::_stateTrajectory, blockProcessing, calibration, DEBUG, ERROR, NO, NONE, OK, pathfinding, server, setMode, stateMachine, Stop_Mode, trajectory.
Referenced by start.
void Core::manualMode()
Referenced by start.
State Core::calibration()
References _stateMachine::_stateCalibration, ImagesP::calibration, ERROR, ImagesP::loadCalib, OK, process, stateMachine.
Referenced by autoVirtualMode.
State Core::blockProcessing(bool is_auto)
References _stateMachine::_stateImageBlock, Bloc::add, ImagesP::all_block, Manager::arrive, Manager::bloc, Manager::car, DEBUG, ERROR, ImagesP::getArrivalPosition, ImagesP::getCarPosition, ImagesP::getSizeMarker, manager, OK, process, Car::setPosition, Arrive::setPosition, ImagesP::startBlock, stateMachine, Manager::update.
Referenced by autoVirtualMode.
State Core::pathfinding()
References _stateMachine::_statePathfinding, Chemin::add, Manager::arrive, Manager::car, Manager::chemin, PathFinding::getChemin, Manager::getGeneralTable, Car::getPosition, Arrive::getPosition, Manager::getSceneCarrer, PathFinding::hasPossibility, manager, NO, OK, path, stateMachine, Manager::update.
Referenced by autoVirtualMode.
State Core::server()
References OK.
Referenced by autoVirtualMode.
State Core::trajectory()
References _stateMachine::_stateTrajectory, OK, stateMachine.
Referenced by autoVirtualMode.
bool Core::forward(float angle)
bool Core::rotation(float angle)