sServer
bool sServer::is_connected
Referenced by isConnected.
key_t sServer::key_send
Referenced by sServer.
int sServer::shmid_send
Referenced by sServer, ~sServer.
shareMemory_t* sServer::data_send
Referenced by sendThingsTo, sServer, ~sServer.
sServer * sServer::instance
Referenced by getInstance.
sServer * sServer::getInstance()
References instance, sServer.
Referenced by main.
bool sServer::sendThingsTo(const char *, char *)
References data_send, _shareM::id_code, _shareM::index, _shareM::tostring.
Referenced by main, sServer.
bool sServer::isConnected()
References is_connected.
sServer::sServer()
References data_send, ID_CONNECTION, _shareM::index, INTER_PROC, key_send, sendThingsTo, shmid_send.
Referenced by getInstance.
sServer::~sServer()
References data_send, shmid_send.