Serveur
Serveur * Serveur::instance
Referenced by getInstance.
std::vector<Client>* Serveur::clients
Referenced by AcceptAndDispatch, getClient, sendToAll, Serveur.
int Serveur::serverSock
Referenced by AcceptAndDispatch, Serveur.
int Serveur::clientSock
struct sockaddr_in serverAddr Serveur::clientAddr
Referenced by AcceptAndDispatch.
char Serveur::buffer[256][256]
Referenced by receive.
Serveur * Serveur::getInstance()
References instance, Serveur.
bool Serveur::stop()
void Serveur::AcceptAndDispatch()
References Manager::car, clientAddr, clients, Manager::getInstance, Car::getPosition, ID_CAR, INVAL_CODE, Client::m_id, Client::m_sock, MAX_CONNECTION_CLIENT, receive, sendToClient, serverSock, STOP_CONN, synchronizeClient, _shareM::tostring, VAL_CODE.
uint16_t Serveur::sendToAll(std::string message)
References clients.
uint16_t Serveur::sendToClient(Client *c, std::string message)
Return nb of byte;
References Client::m_sock.
Referenced by AcceptAndDispatch, synchronizeClient.
Client Serveur::getClient(std::string id)
References clients, _shareM::index.
Serveur::Serveur()
References clients, MAX_CONNECTION_CLIENT, PORT_SERVEUR, serverSock.
Referenced by getInstance.
bool Serveur::synchronizeClient(Client *c)
References ID_CAR, _shareM::id_code, ID_PC, ID_REMOTE, Client::m_id, receive, REQ_CODE, sendToClient.
Referenced by AcceptAndDispatch.
std::string Serveur::receive(Client *c)
References buffer, Client::m_sock.
Referenced by AcceptAndDispatch, synchronizeClient.