Car
Car * Car::instance
Referenced by getInstance.
pair<int8_t, int8_t>* Car::position
Car * Car::getInstance()
References Car, instance.
Referenced by Manager::Manager, unitest_pathfinding.
void Car::sendCommand()
bool Car::setPosition(int8_t x, int8_t y) override
Referenced by Core::blockProcessing, Manager::reset, unitest_pathfinding.
pair<int8_t, int8_t> Car::getPosition() override
Referenced by Serveur::AcceptAndDispatch, Core::drawDebug, Core::pathfinding, toString, unitest_pathfinding, Manager::update.
std::string Car::toString() override
References getPosition.
Referenced by Manager::toString.
Car::~Car()
Car::Car()
Referenced by getInstance.