Bloc
vector<pair<int8_t,int8_t> >* Bloc::list_bloc
Referenced by add, Core::drawDebug, has, remove, toString, Manager::update.
Bloc * Bloc::instance
Referenced by getInstance.
Bloc * Bloc::getInstance()
References Bloc, instance.
Referenced by Manager::Manager, unitest_pathfinding.
bool Bloc::add(int8_t x, int8_t y) override
References list_bloc.
Referenced by Core::blockProcessing, unitest_pathfinding.
bool Bloc::remove(int8_t x, int8_t y) override
References has, list_bloc.
Referenced by unitest_pathfinding.
bool Bloc::set(std::vector< std::pair< int8_t, int8_t >> list)
bool Bloc::has(int8_t x, int8_t y) override
References list_bloc.
Referenced by remove, unitest_pathfinding.
bool Bloc::clear() override
Referenced by Manager::reset.
string Bloc::toString() override
References list_bloc.
Referenced by Manager::toString, unitest_pathfinding.
Bloc::~Bloc()
Bloc::Bloc()
References MAX_BLOC_SCENE.
Referenced by getInstance.