Manager
Car* Manager::car
Referenced by Serveur::AcceptAndDispatch, Core::blockProcessing, Core::drawDebug, Manager, Core::pathfinding, reset, toString, unitest_pathfinding, update.
Bloc* Manager::bloc
Referenced by Core::blockProcessing, Core::drawDebug, Manager, reset, toString, unitest_pathfinding, update.
Chemin* Manager::chemin
Referenced by Core::drawDebug, Manager, Core::pathfinding, reset, toString, unitest_pathfinding, update.
Arrive* Manager::arrive
Referenced by Core::blockProcessing, Core::drawDebug, Manager, Core::pathfinding, reset, toString, unitest_pathfinding, update.
int8_t** Manager::generalTable
Referenced by cleanMatrice, forDevelopper, getCoordonate, getGeneralTable, initScene, update, ~Manager.
int8_t Manager::scenecarrer
Referenced by getSceneCarrer, initScene, Manager, sceneIsDefine, toString, ~Manager.
Manager * Manager::instance
Referenced by getInstance.
Manager * Manager::getInstance()
References instance, Manager.
Referenced by Serveur::AcceptAndDispatch, Core::init, unitest_pathfinding.
int8_t Manager::getCoordonate(int8_t x, int8_t y)
References generalTable.
void Manager::update()
References arrive, ARRIVE_DEF, bloc, BLOC_DEF, car, CAR_DEF, chemin, CHEMIN_DEF, cleanMatrice, generalTable, Car::getPosition, Arrive::getPosition, Bloc::list_bloc, Chemin::list_chemin, sceneIsDefine.
Referenced by Core::blockProcessing, Core::pathfinding, unitest_pathfinding.
int8_t** Manager::getGeneralTable()
References generalTable.
Referenced by Core::pathfinding, unitest_pathfinding.
int8_t Manager::getSceneCarrer()
References scenecarrer.
Referenced by cleanMatrice, forDevelopper, Core::pathfinding, unitest_pathfinding.
bool Manager::initScene(int8_t nb_carrer)
References generalTable, scenecarrer.
Referenced by Core::init, unitest_pathfinding.
bool Manager::sceneIsDefine()
References scenecarrer.
Referenced by update.
std::string Manager::toString()
References arrive, bloc, car, chemin, scenecarrer, Car::toString, Chemin::toString, Arrive::toString, Bloc::toString.
std::string Manager::forDevelopper()
References generalTable, getSceneCarrer.
Referenced by unitest_pathfinding.
Manager::~Manager()
References generalTable, scenecarrer.
void Manager::reset()
References arrive, bloc, car, chemin, cleanMatrice, Chemin::clear, Bloc::clear, Car::setPosition, Arrive::setPosition.
Referenced by Core::setMode.
void Manager::cleanMatrice()
References generalTable, getSceneCarrer.
Referenced by reset, update.
Manager::Manager()
References arrive, bloc, car, chemin, Car::getInstance, Chemin::getInstance, Arrive::getInstance, Bloc::getInstance, scenecarrer.
Referenced by getInstance.